language: node_js

services:
  - docker

node_js:
  - '11'

env:
  global:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
cache: npm

filter_secrets: false

before_deploy:
  - git config --local user.name "Manuel-777"
  - git config --local user.email "manuel.etchegaray7@gmail.com"

jobs:
  include:
    - stage: Windows build
      os: windows
      env: YARN_GPG=no
      script:
        - npm test
        - npm run dist
      deploy:
        provider: releases
        file_glob: true
        skip_cleanup: true
        prerelease: true
        draft: $DRAFT
        api_key:
          secure: $GH_TOKEN
        file: dist/*
        on:
          tags: $TAGS
          repo: Manuel-777/MTG-Arena-Tool
    - stage: Linux build
      os: linux
      dist: xenial
      sudo: required
      script:
        - npm run dist
      deploy:
        provider: releases
        file_glob: true
        skip_cleanup: true
        prerelease: true
        draft: $DRAFT
        api_key:
          secure: $GH_TOKEN
        file: dist/*
        on:
          tags: $TAGS
          repo: Manuel-777/MTG-Arena-Tool
    - stage: Mac build
      os: osx
      script:
        - npm run dist
      deploy:
        provider: releases
        file_glob: true
        skip_cleanup: true
        prerelease: true
        draft: $DRAFT
        api_key:
          secure: $GH_TOKEN
        file: dist/*
        on:
          tags: $TAGS
          repo: Manuel-777/MTG-Arena-Tool