import settingsSlice from "./slices/settingsSlice";
import playerDataSlice from "./slices/playerDataSlice";
import appSettingsSlice from "./slices/appSettingsSlice";
import rendererSlice from "./slices/rendererSlice";
import hoverSlice from "./slices/hoverSlice";
import loginSlice from "./slices/loginSlice";
import homeSlice from "./slices/homeSlice";
import collectionSlice from "./slices/collectionSlice";
import exploreSlice from "./slices/exploreSlice";
import matchesSlice from "./slices/matchesSlice";
import eventsSlice from "./slices/eventsSlice";

const actions: Record<string, (arg: any) => any> = {};
actions["SET_SETTINGS"] = settingsSlice.actions.setSettings;
actions["SET_APP_SETTINGS"] = appSettingsSlice.actions.setAppSettings;
actions["SET_ARCHIVED"] = rendererSlice.actions.setArchived;
actions["SET_BACK_COLOR"] = rendererSlice.actions.setBackgroundColor;
actions["SET_BACK_GRPID"] = rendererSlice.actions.setBackgroundGrpId;
actions["SET_BACK_IMAGE"] = rendererSlice.actions.setBackgroundImage;
actions["SET_LOADING"] = rendererSlice.actions.setLoading;
actions["SET_NO_LOG"] = rendererSlice.actions.setNoLog;
actions["SET_OFFLINE"] = rendererSlice.actions.setOffline;
actions["SET_PATREON"] = rendererSlice.actions.setPatreon;
actions["SET_POPUP"] = rendererSlice.actions.setPopup;
actions["SET_SHARE_DIALOG"] = rendererSlice.actions.setShareDialog;
actions["SET_SHARE_DIALOG_OPEN"] = rendererSlice.actions.setShareDialogOpen;
actions["SET_SHARE_DIALOG_URL"] = rendererSlice.actions.setShareDialogUrl;
actions["SET_SUBNAV"] = rendererSlice.actions.setSubNav;
actions["SET_TOPARTIST"] = rendererSlice.actions.setTopArtist;
actions["SET_TOPNAV"] = rendererSlice.actions.setTopNav;
actions["SET_UPDATE_STATE"] = rendererSlice.actions.setUpdateState;
actions["SET_HOVER_IN"] = hoverSlice.actions.setHoverIn;
actions["SET_HOVER_OUT"] = hoverSlice.actions.setHoverOut;
actions["SET_CAN_LOGIN"] = loginSlice.actions.setCanLogin;
actions["SET_LOGIN_EMAIL"] = loginSlice.actions.setLoginEmail;
actions["SET_LOGIN_FORM"] = loginSlice.actions.setLoginForm;
actions["SET_LOGIN_PASSWORD"] = loginSlice.actions.setLoginPassword;
actions["SET_LOGIN_REMEMBER"] = loginSlice.actions.setLoginRemember;
actions["SET_LOGIN_STATE"] = loginSlice.actions.setLoginState;
actions["SET_HOME_DATA"] = homeSlice.actions.setHomeData;
actions["SET_BOOSTER_WIN_FACTOR"] = collectionSlice.actions.setBoosterWinFactor;
actions["SET_COUNT_MODE"] = collectionSlice.actions.setCountMode;
actions["SET_FUTURE_BOOSTERS"] = collectionSlice.actions.setFutureBoosters;
actions["SET_MYTHIC_DRAFT_FACTOR"] =
  collectionSlice.actions.setMythicDraftFactor;
actions["SET_RARE_DRAFT_FACTOR"] = collectionSlice.actions.setRareDraftFactor;
actions["SET_ACTIVE_EVENTS"] = exploreSlice.actions.setActiveEvents;
actions["SET_EXPLORE_DATA"] = exploreSlice.actions.setExploreData;
actions["SET_EXPLORE_FILTERS"] = exploreSlice.actions.setExploreFilters;
actions["SET_EXPLORE_FILTERS_SKIP"] =
  exploreSlice.actions.setExploreFiltersSkip;
actions["SET_MATCH"] = matchesSlice.actions.setMatch;
actions["SET_MANY_MATCHES"] = matchesSlice.actions.setManyMatches;
actions["SET_EVENTS"] = eventsSlice.actions.setEvent;
actions["SET_MANY_EVENTS"] = eventsSlice.actions.setManyEvents;
actions["SET_PLAYER_ID"] = playerDataSlice.actions.setPlayerId;
actions["SET_PLAYER_NAME"] = playerDataSlice.actions.setPlayerName;
actions["SET_ARENA_VERSION"] = playerDataSlice.actions.setArenaVersion;

export default actions;
